"""empty message

Revision ID: 053293c7ff57
Revises: dd1883873ddd
Create Date: 2021-08-31 09:09:21.724636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053293c7ff57'
down_revision = 'dd1883873ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sendername', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sendername')
    # ### end Alembic commands ###
