"""empty message

Revision ID: 0b418e7332c5
Revises: 277274f960f6
Create Date: 2021-08-08 02:10:07.778443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b418e7332c5'
down_revision = '277274f960f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('banner', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('contact_number', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('adderss', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('loc_state', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('personal_details_complete', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('tagp1', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('tagp2', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('tagp3', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('preferences_complete', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_profile_company', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('event_details_complete', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'profile_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_type', mysql.VARCHAR(length=8), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'event_details_complete')
    op.drop_column('user', 'is_profile_company')
    op.drop_column('user', 'preferences_complete')
    op.drop_column('user', 'tagp3')
    op.drop_column('user', 'tagp2')
    op.drop_column('user', 'tagp1')
    op.drop_column('user', 'personal_details_complete')
    op.drop_column('user', 'country')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'loc_state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'adderss')
    op.drop_column('user', 'contact_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('event', 'banner')
    op.drop_table('customer')
    # ### end Alembic commands ###
