"""empty message

Revision ID: 126caed16023
Revises: 0b418e7332c5
Create Date: 2021-08-14 07:29:33.803530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '126caed16023'
down_revision = '0b418e7332c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    op.add_column('event', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('event', sa.Column('time_end', sa.Time(), nullable=True))
    op.add_column('event', sa.Column('attendee1', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount1', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee2', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount2', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee3', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount3', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee4', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount4', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'discount4')
    op.drop_column('event', 'attendee4')
    op.drop_column('event', 'discount3')
    op.drop_column('event', 'attendee3')
    op.drop_column('event', 'discount2')
    op.drop_column('event', 'attendee2')
    op.drop_column('event', 'discount1')
    op.drop_column('event', 'attendee1')
    op.drop_column('event', 'time_end')
    op.drop_column('event', 'time')
    op.drop_column('event', 'date_end')
    op.create_table('offer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('attendee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('discount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='offer_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
