"""empty message

Revision ID: 29abe1419e0f
Revises: f9137b604a65
Create Date: 2021-08-29 23:22:25.577278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29abe1419e0f'
down_revision = 'f9137b604a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('attendee5', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount5', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee6', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount6', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee7', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount7', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('attendee8', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('discount8', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'discount8')
    op.drop_column('event', 'attendee8')
    op.drop_column('event', 'discount7')
    op.drop_column('event', 'attendee7')
    op.drop_column('event', 'discount6')
    op.drop_column('event', 'attendee6')
    op.drop_column('event', 'discount5')
    op.drop_column('event', 'attendee5')
    # ### end Alembic commands ###
