"""empty message

Revision ID: 3424f0c297fe
Revises: 053293c7ff57
Create Date: 2021-09-01 03:38:24.976111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3424f0c297fe'
down_revision = '053293c7ff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_acc_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'user', ['stripe_acc_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'stripe_acc_id')
    # ### end Alembic commands ###
