"""empty message

Revision ID: c69cb7934c8c
Revises: 
Create Date: 2021-07-31 19:10:42.691546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69cb7934c8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_type', sa.String(length=8), nullable=True),
    sa.Column('company_details', sa.String(length=1800), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=False),
    sa.Column('is_account_verified', sa.Boolean(), nullable=False),
    sa.Column('times_logged_in', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1800), nullable=False),
    sa.Column('banner', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('days', sa.String(length=255), nullable=False),
    sa.Column('pre_knowledge', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=255), nullable=True),
    sa.Column('equipment', sa.String(length=255), nullable=True),
    sa.Column('min_tickets', sa.Integer(), nullable=True),
    sa.Column('attendee_amount', sa.Integer(), nullable=False),
    sa.Column('offers_bool', sa.Boolean(), nullable=False),
    sa.Column('fee_cancel', sa.Boolean(), nullable=False),
    sa.Column('prioritize', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('tag_title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1800), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('offer_title', sa.String(length=32), nullable=False),
    sa.Column('offer_price', sa.Integer(), nullable=False),
    sa.Column('offer_image', sa.String(length=20), nullable=False),
    sa.Column('offer_discount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    op.drop_table('comment')
    op.drop_table('tag')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
