"""empty message

Revision ID: dd1883873ddd
Revises: cc0d40161993
Create Date: 2021-08-30 03:00:32.956025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1883873ddd'
down_revision = 'cc0d40161993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('thumb', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
