"""empty message

Revision ID: f8684cf0cb47
Revises: e301a70274e9
Create Date: 2021-08-06 20:45:53.671975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8684cf0cb47'
down_revision = 'e301a70274e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('attendee', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('discount', sa.Integer(), nullable=True))
    op.alter_column('offer', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('offer_ibfk_1', 'offer', type_='foreignkey')
    op.drop_column('offer', 'offer_title')
    op.drop_column('offer', 'offer_discount')
    op.drop_column('offer', 'creator_id')
    op.drop_column('offer', 'offer_price')
    op.drop_column('offer', 'offer_image')
    op.drop_column('offer', 'is_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('offer_image', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('offer', sa.Column('offer_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('offer_discount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('offer_title', mysql.VARCHAR(length=32), nullable=False))
    op.create_foreign_key('offer_ibfk_1', 'offer', 'user', ['creator_id'], ['id'])
    op.alter_column('offer', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('offer', 'discount')
    op.drop_column('offer', 'attendee')
    # ### end Alembic commands ###
